In [2]:
import json
import pandas as pd

In [3]:
with open(r'C:\Users\bitse\YandexDisk\Rushim\rushim\info_2.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
    df = pd.json_normalize(data)

In [4]:
df = pd.DataFrame(df)

In [5]:
df_excel = pd.read_excel(r'C:\Users\bitse\YandexDisk\Rushim\rushim\rushim\spiders\result.xlsx')

In [6]:
df_excel.head(10)

,product,category,price,trademark,country,description,CAS,INCI,manufacturer,packing
0,"Изопропиловый спирт (Пропанол-2), хч, фас 20 л...",Реактивы и хим. сырье,4260.00,...,...,...,...,...,...,...
1,"Калий фосфорнокислый 2-замещенный 3 водн, чда/...",Реактивы и хим. сырье,693.00,...,...,...,...,...,...,...
2,"Натрий салициловокислый, ч, цена за 1 кг",Реактивы и хим. сырье,963.00,...,...,...,...,...,...,...
3,"Крахмал текстильный Aprin, упак 1 кг - 80 руб",Реактивы и хим. сырье,110.00,...,...,...,...,...,...,...
4,"Крахмал водорастворимый, чда СВЕЖИЙ, упак 0,5 ...",Реактивы и хим. сырье,798.00,...,...,...,...,...,...,...
5,"Бумага упаковочная с рисунком, цена за 1 кг",Реактивы и хим. сырье,45.00,...,...,...,...,...,...,...
6,"Метиламин раствор 38 %, от 95 л (5 кан по 19 л...",Реактивы и хим. сырье,1160.00,...,...,...,...,...,...,...
7,"Аммоний азотнокислый, ч, NH4NO3 цена за 1 кг",Реактивы и хим. сырье,428.00,...,...,...,...,...,...,...
8,"Глиоксиловая кислота, 50 % раствор, имп, упак....",Реактивы и хим. сырье,32240.00,...,...,...,...,...,...,...
9,Диметиламинобензальдегид-пара ч,Реактивы и хим. сырье,9300.00,...,...,...,...,...,...,...

In [7]:
df_10_strings = df_excel.head(10)

In [8]:
df_10_strings

,product,category,price,trademark,country,description,CAS,INCI,manufacturer,packing
0,"Изопропиловый спирт (Пропанол-2), хч, фас 20 л...",Реактивы и хим. сырье,4260.00,...,...,...,...,...,...,...
1,"Калий фосфорнокислый 2-замещенный 3 водн, чда/...",Реактивы и хим. сырье,693.00,...,...,...,...,...,...,...
2,"Натрий салициловокислый, ч, цена за 1 кг",Реактивы и хим. сырье,963.00,...,...,...,...,...,...,...
3,"Крахмал текстильный Aprin, упак 1 кг - 80 руб",Реактивы и хим. сырье,110.00,...,...,...,...,...,...,...
4,"Крахмал водорастворимый, чда СВЕЖИЙ, упак 0,5 ...",Реактивы и хим. сырье,798.00,...,...,...,...,...,...,...
5,"Бумага упаковочная с рисунком, цена за 1 кг",Реактивы и хим. сырье,45.00,...,...,...,...,...,...,...
6,"Метиламин раствор 38 %, от 95 л (5 кан по 19 л...",Реактивы и хим. сырье,1160.00,...,...,...,...,...,...,...
7,"Аммоний азотнокислый, ч, NH4NO3 цена за 1 кг",Реактивы и хим. сырье,428.00,...,...,...,...,...,...,...
8,"Глиоксиловая кислота, 50 % раствор, имп, упак....",Реактивы и хим. сырье,32240.00,...,...,...,...,...,...,...
9,Диметиламинобензальдегид-пара ч,Реактивы и хим. сырье,9300.00,...,...,...,...,...,...,...

In [9]:
df_product = df_excel['product'].head(10)

In [10]:
df_product

0    Изопропиловый спирт (Пропанол-2), хч, фас 20 л...
1    Калий фосфорнокислый 2-замещенный 3 водн, чда/...
2             Натрий салициловокислый, ч, цена за 1 кг
3        Крахмал текстильный Aprin, упак 1 кг - 80 руб
4    Крахмал водорастворимый, чда СВЕЖИЙ, упак 0,5 ...
5          Бумага упаковочная с рисунком, цена за 1 кг
6    Метиламин раствор 38 %, от 95 л (5 кан по 19 л...
7         Аммоний азотнокислый, ч, NH4NO3 цена за 1 кг
8    Глиоксиловая кислота, 50 % раствор, имп, упак....
9                      Диметиламинобензальдегид-пара ч
Name: product, dtype: object

In [19]:
for row in df_product:
    ready_string = row.split(',')[0]
    #print(ready_string)
    df_10_strings['product'] = ready_string
    print(df_10_strings['product'])

0    Изопропиловый спирт (Пропанол-2)
1    Изопропиловый спирт (Пропанол-2)
2    Изопропиловый спирт (Пропанол-2)
3    Изопропиловый спирт (Пропанол-2)
4    Изопропиловый спирт (Пропанол-2)
5    Изопропиловый спирт (Пропанол-2)
6    Изопропиловый спирт (Пропанол-2)
7    Изопропиловый спирт (Пропанол-2)
8    Изопропиловый спирт (Пропанол-2)
9    Изопропиловый спирт (Пропанол-2)
Name: product, dtype: object
0    Калий фосфорнокислый 2-замещенный 3 водн
1    Калий фосфорнокислый 2-замещенный 3 водн
2    Калий фосфорнокислый 2-замещенный 3 водн
3    Калий фосфорнокислый 2-замещенный 3 водн
4    Калий фосфорнокислый 2-замещенный 3 водн
5    Калий фосфорнокислый 2-замещенный 3 водн
6    Калий фосфорнокислый 2-замещенный 3 водн
7    Калий фосфорнокислый 2-замещенный 3 водн
8    Калий фосфорнокислый 2-замещенный 3 водн
9    Калий фосфорнокислый 2-замещенный 3 водн
Name: product, dtype: object
0    Натрий салициловокислый
1    Натрий салициловокислый
2    Натрий салициловокислый
3    Натрий салициловокислый
4    Натрий салициловокислый
5    Натрий салициловокислый
6    Натрий салициловокислый
7    Натрий салициловокислый
8    Натрий салициловокислый
9    Натрий салициловокислый
Name: product, dtype: object
0    Крахмал текстильный Aprin
1    Крахмал текстильный Aprin
2    Крахмал текстильный Aprin
3    Крахмал текстильный Aprin
4    Крахмал текстильный Aprin
5    Крахмал текстильный Aprin
6    Крахмал текстильный Aprin
7    Крахмал текстильный Aprin
8    Крахмал текстильный Aprin
9    Крахмал текстильный Aprin
Name: product, dtype: object
0    Крахмал водорастворимый
1    Крахмал водорастворимый
2    Крахмал водорастворимый
3    Крахмал водорастворимый
4    Крахмал водорастворимый
5    Крахмал водорастворимый
6    Крахмал водорастворимый
7    Крахмал водорастворимый
8    Крахмал водорастворимый
9    Крахмал водорастворимый
Name: product, dtype: object
0    Бумага упаковочная с рисунком
1    Бумага упаковочная с рисунком
2    Бумага упаковочная с рисунком
3    Бумага упаковочная с рисунком
4    Бумага упаковочная с рисунком
5    Бумага упаковочная с рисунком
6    Бумага упаковочная с рисунком
7    Бумага упаковочная с рисунком
8    Бумага упаковочная с рисунком
9    Бумага упаковочная с рисунком
Name: product, dtype: object
0    Метиламин раствор 38 %
1    Метиламин раствор 38 %
2    Метиламин раствор 38 %
3    Метиламин раствор 38 %
4    Метиламин раствор 38 %
5    Метиламин раствор 38 %
6    Метиламин раствор 38 %
7    Метиламин раствор 38 %
8    Метиламин раствор 38 %
9    Метиламин раствор 38 %
Name: product, dtype: object
0    Аммоний азотнокислый
1    Аммоний азотнокислый
2    Аммоний азотнокислый
3    Аммоний азотнокислый
4    Аммоний азотнокислый
5    Аммоний азотнокислый
6    Аммоний азотнокислый
7    Аммоний азотнокислый
8    Аммоний азотнокислый
9    Аммоний азотнокислый
Name: product, dtype: object
0    Глиоксиловая кислота
1    Глиоксиловая кислота
2    Глиоксиловая кислота
3    Глиоксиловая кислота
4    Глиоксиловая кислота
5    Глиоксиловая кислота
6    Глиоксиловая кислота
7    Глиоксиловая кислота
8    Глиоксиловая кислота
9    Глиоксиловая кислота
Name: product, dtype: object
0    Диметиламинобензальдегид-пара ч
1    Диметиламинобензальдегид-пара ч
2    Диметиламинобензальдегид-пара ч
3    Диметиламинобензальдегид-пара ч
4    Диметиламинобензальдегид-пара ч
5    Диметиламинобензальдегид-пара ч
6    Диметиламинобензальдегид-пара ч
7    Диметиламинобензальдегид-пара ч
8    Диметиламинобензальдегид-пара ч
9    Диметиламинобензальдегид-пара ч
Name: product, dtype: object

C:\Users\bitse\AppData\Local\Temp\ipykernel_7344\120679227.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_10_strings['product'] = ready_string

In [17]:
for i in df_product:
    i = i.split()
    #print(i)
    for s in i:
        if s == 'упак' or s == 'упаковку':
            df_10_strings['packing'] = 'упак'
            print(df_10_strings['packing'])

0    упак
1    упак
2    упак
3    упак
4    упак
5    упак
6    упак
7    упак
8    упак
9    упак
Name: packing, dtype: object
0    упак
1    упак
2    упак
3    упак
4    упак
5    упак
6    упак
7    упак
8    упак
9    упак
Name: packing, dtype: object
0    упак
1    упак
2    упак
3    упак
4    упак
5    упак
6    упак
7    упак
8    упак
9    упак
Name: packing, dtype: object
0    упак
1    упак
2    упак
3    упак
4    упак
5    упак
6    упак
7    упак
8    упак
9    упак
Name: packing, dtype: object

C:\Users\bitse\AppData\Local\Temp\ipykernel_7344\1761610174.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_10_strings['packing'] = 'упак'