In [60]:
import pandas as pd
import re

In [61]:
df_e = pd.read_excel(r'C:\Users\Dmitriy\YandexDisk\Rushim\rushim\rushim\spiders\result.xlsx')

In [62]:
df_e

,product,category,price,trademark,country,description,CAS,INCI,manufacturer,packing
0,"Изопропиловый спирт (Пропанол-2), хч, фас 20 л...",Реактивы и хим. сырье,4260.00,...,...,...,...,...,...,...
1,"Калий фосфорнокислый 2-замещенный 3 водн, чда/...",Реактивы и хим. сырье,693.00,...,...,...,...,...,...,...
2,"Натрий салициловокислый, ч, цена за 1 кг",Реактивы и хим. сырье,963.00,...,...,...,...,...,...,...
3,"Крахмал текстильный Aprin, упак 1 кг - 80 руб",Реактивы и хим. сырье,110.00,...,...,...,...,...,...,...
4,"Крахмал водорастворимый, чда СВЕЖИЙ, упак 0,5 ...",Реактивы и хим. сырье,798.00,...,...,...,...,...,...,...
...,...,...,...,...,...,...,...,...,...,...
796,"Бензилбензоат, упак 0,5 кг цена за упак.",Реактивы и хим. сырье,570.00,...,...,...,...,...,...,...
797,"Дифениламин имп, аналог чда, упак 25 кг, цена ...",Реактивы и хим. сырье,2900.00,...,...,...,...,...,...,...
798,"Бентонит (глинопорошок для виноделия), упак 25...",Реактивы и хим. сырье,1985.00,...,...,...,...,...,...,...
799,"Калий дихромат, ч, цена за 1 кг",Реактивы и хим. сырье,860.00,...,...,...,...,...,...,...
800,"Уранин А (индикатор, сан. заключение), заказ 2...",Реактивы и хим. сырье,7319.00,...,...,...,...,...,...,...

In [63]:
df_10 = df_e.head(10)

In [64]:
df_10

,product,category,price,trademark,country,description,CAS,INCI,manufacturer,packing
0,"Изопропиловый спирт (Пропанол-2), хч, фас 20 л...",Реактивы и хим. сырье,4260.00,...,...,...,...,...,...,...
1,"Калий фосфорнокислый 2-замещенный 3 водн, чда/...",Реактивы и хим. сырье,693.00,...,...,...,...,...,...,...
2,"Натрий салициловокислый, ч, цена за 1 кг",Реактивы и хим. сырье,963.00,...,...,...,...,...,...,...
3,"Крахмал текстильный Aprin, упак 1 кг - 80 руб",Реактивы и хим. сырье,110.00,...,...,...,...,...,...,...
4,"Крахмал водорастворимый, чда СВЕЖИЙ, упак 0,5 ...",Реактивы и хим. сырье,798.00,...,...,...,...,...,...,...
5,"Бумага упаковочная с рисунком, цена за 1 кг",Реактивы и хим. сырье,45.00,...,...,...,...,...,...,...
6,"Метиламин раствор 38 %, от 95 л (5 кан по 19 л...",Реактивы и хим. сырье,1160.00,...,...,...,...,...,...,...
7,"Аммоний азотнокислый, ч, NH4NO3 цена за 1 кг",Реактивы и хим. сырье,428.00,...,...,...,...,...,...,...
8,"Глиоксиловая кислота, 50 % раствор, имп, упак....",Реактивы и хим. сырье,32240.00,...,...,...,...,...,...,...
9,Диметиламинобензальдегид-пара ч,Реактивы и хим. сырье,9300.00,...,...,...,...,...,...,...

In [65]:
df_10['product']

0    Изопропиловый спирт (Пропанол-2), хч, фас 20 л...
1    Калий фосфорнокислый 2-замещенный 3 водн, чда/...
2             Натрий салициловокислый, ч, цена за 1 кг
3        Крахмал текстильный Aprin, упак 1 кг - 80 руб
4    Крахмал водорастворимый, чда СВЕЖИЙ, упак 0,5 ...
5          Бумага упаковочная с рисунком, цена за 1 кг
6    Метиламин раствор 38 %, от 95 л (5 кан по 19 л...
7         Аммоний азотнокислый, ч, NH4NO3 цена за 1 кг
8    Глиоксиловая кислота, 50 % раствор, имп, упак....
9                      Диметиламинобензальдегид-пара ч
Name: product, dtype: object

In [66]:
print(type(df_10))

<class 'pandas.core.frame.DataFrame'>

In [67]:
string_10 = (i.split(',') for i in df_10['product'])

<generator object <genexpr> at 0x00000238044EE5A0>

In [97]:
for row in df_10['product']:
    #print(row, type(row))
    i = row.split(',')[0]
    print(i)

Изопропиловый спирт (Пропанол-2)
Калий фосфорнокислый 2-замещенный 3 водн
Натрий салициловокислый
Крахмал текстильный Aprin
Крахмал водорастворимый
Бумага упаковочная с рисунком
Метиламин раствор 38 %
Аммоний азотнокислый
Глиоксиловая кислота
Диметиламинобензальдегид-пара ч

In [101]:
for row in df_10['product']:
    if 'упак' in row or 'упаковка' in row:
        print(row)

Изопропиловый спирт (Пропанол-2), хч, фас 20 л, цена за упаковку
Крахмал текстильный Aprin, упак 1 кг - 80 руб
Крахмал водорастворимый, чда СВЕЖИЙ, упак 0,5 кг, цена за упаковку
Бумага упаковочная с рисунком, цена за 1 кг
Глиоксиловая кислота, 50 % раствор, имп, упак. 5,0 кг - под заказ