In [1]:
import pandas as pd

In [5]:
df = pd.read_csv(r'U:\SNABIO\chemkomplekt\chemkomplekt\chem_sel.csv')

In [6]:
df

,title,category,country,price
0,Аммоний вольфрамовокислый чда,NaN,порошок,2 300
1,Фенолфталеин,селективные реактивы,NaN,3 500
2,Железо (II) сернокислое 9-водное ч,селективные реактивы,NaN,290
3,Кислота борная хч,NaN,инсектицид,160
4,Формалин тех. в/с,селективные реактивы,NaN,160
...,...,...,...,...
736,Кислота хлорная хч,Хлорная кислота является одной из сильнейших н...,Китай,3 600
737,Калий двухромовокислый чда,NaN,NaN,700
738,Кислота бензойная,NaN,Россия,300
739,Бутилацетат чда (Бутиловый эфир уксусной кислоты),NaN,NaN,450
740,"Барий хромовокислый, хромат бария",NaN,NaN,1 000

In [24]:
df_filled = df.fillna('')  # Fill NaN values with empty strings

In [25]:
df_filled

,title,category,country,price
0,Аммоний вольфрамовокислый чда,,порошок,2 300
1,Фенолфталеин,селективные реактивы,,3 500
2,Железо (II) сернокислое 9-водное ч,селективные реактивы,,290
3,Кислота борная хч,,инсектицид,160
4,Формалин тех. в/с,селективные реактивы,,160
...,...,...,...,...
736,Кислота хлорная хч,Хлорная кислота является одной из сильнейших н...,Китай,3 600
737,Калий двухромовокислый чда,,,700
738,Кислота бензойная,,Россия,300
739,Бутилацетат чда (Бутиловый эфир уксусной кислоты),,,450
740,"Барий хромовокислый, хромат бария",,,1 000

In [7]:
df.to_excel('chem_sel.xlsx')

In [12]:
df_1 = pd.read_excel(r'U:\SNABIO\chemkomplekt\chemkomplekt\spiders\chem_sel.xlsx')

In [14]:
df_1

,Unnamed: 0,title,category,country,price
0,0,Аммоний вольфрамовокислый чда,NaN,порошок,2 300
1,1,Фенолфталеин,селективные реактивы,NaN,3 500
2,2,Железо (II) сернокислое 9-водное ч,селективные реактивы,NaN,290
3,3,Кислота борная хч,NaN,инсектицид,160
4,4,Формалин тех. в/с,селективные реактивы,NaN,160
...,...,...,...,...,...
736,736,Кислота хлорная хч,Хлорная кислота является одной из сильнейших н...,Китай,3 600
737,737,Калий двухромовокислый чда,NaN,NaN,700
738,738,Кислота бензойная,NaN,Россия,300
739,739,Бутилацетат чда (Бутиловый эфир уксусной кислоты),NaN,NaN,450
740,740,"Барий хромовокислый, хромат бария",NaN,NaN,1 000

In [15]:
data = {'column_name': ['category', 'name']}

In [16]:
df_3 = pd.DataFrame(data)

In [17]:
counts = df['category'].value_counts()

In [18]:
print(counts)

category
селективные реактивы                                                                                                                  484
необратимый                                                                                                                             3
нет                                                                                                                                     2
Порошок                                                                                                                                 1
                                                                                                                                        1
зеленый                                                                                                                                 1
да                                                                                                                                      1
Хлорная кислота является одной из сильнейших неорганических кислот, в ее среде даже кислотные соединения ведут себя как основания.      1
Name: count, dtype: int64

In [20]:
counts = df['name'].value_counts()

KeyError: 'name'

In [21]:
print(counts)

category
селективные реактивы                                                                                                                  484
необратимый                                                                                                                             3
нет                                                                                                                                     2
Порошок                                                                                                                                 1
                                                                                                                                        1
зеленый                                                                                                                                 1
да                                                                                                                                      1
Хлорная кислота является одной из сильнейших неорганических кислот, в ее среде даже кислотные соединения ведут себя как основания.      1
Name: count, dtype: int64