In [1]:
import pandas as pd

In [5]:
df = pd.read_csv(r'U:\SNABIO\him_tech\himtech.csv')

In [6]:
df

       category                                  name  price
0    Флокулянты               Флокулянт Praestol 2530    350
1    Флокулянты           Флокулянт Superfloc A120PWG    350
2    Флокулянты           Флокулянт Superfloc A120HMW    350
3    Флокулянты              Флокулянт Superfloc A120    350
4    Флокулянты           Флокулянт Superfloc A110PWG    350
..          ...                                   ...    ...
589  Флокулянты           Флокулянт SPECFLOK A7926-10      0
590  Флокулянты               Флокулянт Praestol 2505    350
591  Флокулянты            Флокулянт Flopam AN 956 SH    350
592  Флокулянты               Флокулянт Praestol 2515    350
593  Флокулянты  Флокулянт Magnafloc (Магнафлок) 10-A    350

[594 rows x 3 columns]

In [10]:
df.to_excel('him_tech.xlsx')

In [12]:
df_1 = pd.read_excel(r'U:\SNABIO\him_tech\him_tech\spiders\him_tech.xlsx')

In [13]:
df_1

     Unnamed: 0    category                                  name  price
0             0  Флокулянты               Флокулянт Praestol 2530    350
1             1  Флокулянты           Флокулянт Superfloc A120PWG    350
2             2  Флокулянты           Флокулянт Superfloc A120HMW    350
3             3  Флокулянты              Флокулянт Superfloc A120    350
4             4  Флокулянты           Флокулянт Superfloc A110PWG    350
..          ...         ...                                   ...    ...
589         589  Флокулянты           Флокулянт SPECFLOK A7926-10      0
590         590  Флокулянты               Флокулянт Praestol 2505    350
591         591  Флокулянты            Флокулянт Flopam AN 956 SH    350
592         592  Флокулянты               Флокулянт Praestol 2515    350
593         593  Флокулянты  Флокулянт Magnafloc (Магнафлок) 10-A    350

[594 rows x 4 columns]